version: '3.8'
services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: weaviate/weaviate:latest
    ports:
      - "8080:8080"
