"""Logical instrument manifest with bounded attribute sets (plan §8).

Frozen declarations only — real instruments are created from this manifest
by `telemetry.py` when broad OTel is enabled. Freezing names/attributes here
lets tests catch accidental renames and cardinality growth before they ship
(plan §8: "Freeze their final names in `metrics.py` before use").

Every attribute set is finite and documented; labels never carry IDs, model
names under dynamic routing, timestamps, URLs, content, exception bodies, or
concrete paths.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import StrEnum

from therapy.observability.model import (
    Component,
    Destination,
    InteractionOperation,
    LanguageGroup,
    Modality,
    Outcome,
    Provider,
    WorkloadClass,
)


class InstrumentKind(StrEnum):
    COUNTER = "counter"
    HISTOGRAM = "histogram"
    GAUGE = "gauge"


@dataclass(frozen=True, slots=True)
class InstrumentSpec:
    name: str
    kind: InstrumentKind
    unit: str
    #: Attribute name -> complete allowed values. Every label is closed-world;
    #: callers cannot create a new series merely by matching a string shape.
    attributes: dict[str, tuple[str, ...]] = field(default_factory=lambda: {})


_STAGES = ("vad", "stt", "persist_user", "context", "llm", "persist_assistant", "tts", "output")
_CAPTURE_STATUS = ("journaled", "exported", "incomplete", "failed")
_LLM_RESULT = ("ok", "empty", "truncated", "language_mismatch", "invalid_structured")
_COUNT_BUCKETS = ("0", "1-9", "10-99", "100-999", "1000+")
_OUTCOME_BASIC = ("success", "error", "timeout", "rejected")
_OUTCOMES = tuple(item.value for item in Outcome)
_PROVIDERS = tuple(item.value for item in Provider)
_OPERATIONS = tuple(item.value for item in InteractionOperation) + ("unknown",)
_COMPONENTS = tuple(item.value for item in Component)
_LANGUAGE_GROUPS = tuple(item.value for item in LanguageGroup)
_MODALITIES = tuple(item.value for item in Modality)
_WORKLOAD_CLASSES = tuple(item.value for item in WorkloadClass)
_DESTINATIONS = tuple(item.value for item in Destination)
_CLIENT_EVENT_NAMES = (
    "media_permission", "signaling_state", "ice_state", "data_channel_state",
    "peer_state", "transcript_echo_timeout", "playback_failure", "disconnect",
    "webrtc_sample", "sw_lifecycle", "shell_fetch", "cache_fallback",
    "cache_recovery", "push_lifecycle",
)
_CLIENT_OUTCOMES = (
    "success", "error", "timeout", "fallback", "recovered", "denied",
    "granted", "received", "shown", "clicked", "connected", "disconnected",
    "failed", "installed", "activated", "refreshed", "deactivated",
)
_STORAGE_OPERATIONS = (
    "create_session", "end_session", "delete_session", "reopen_session",
    "add_turn", "ensure_title", "ensure_recap", "ingest_bytes", "reindex",
    "query", "unknown",
)
_SOVEREIGNTY_STAGES = (
    "tables", "files", "json", "validate", "stage_files", "backup_database",
    "backup_files", "database_clear", "replace_files", "refresh_keys",
    "rollback_database", "rollback_files", "rollback_refresh_keys",
    "cleanup_database_backup", "cleanup_files_backup", "cleanup_staged_files",
    "table_sessions", "table_turns", "table_nodes", "table_edges",
    "table_node_aliases", "table_claim_evidence", "table_lifecycle_events",
    "table_boundaries", "table_privacy_purge_events", "table_tombstones",
    "table_distillation_runs", "table_observation_inbox",
    "table_pending_insights", "table_insight_history",
    "table_semantic_embeddings", "table_proactivity_settings",
    "table_proactivity_jobs", "table_push_subscriptions",
    "table_in_app_messages", "table_digests", "table_research_documents",
    "table_research_blocks", "table_research_index",
    "proactivity", "research", "model", "sessions_audio",
    "private_files_backups", "wal_checkpoint", "vacuum",
)

INSTRUMENTS: tuple[InstrumentSpec, ...] = (
    # --- voice/service ---
    InstrumentSpec("therapy_voice_connections_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("success", "conflict", "invalid", "no_answer",
                                "unavailable", "unknown"),
                    "reason": ("negotiate", "unknown")}),
    InstrumentSpec("therapy_voice_active_connections", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_voice_pipeline_active", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_voice_pipeline_transitions_total", InstrumentKind.COUNTER,
                   "1", {"transition": ("claim", "owns", "release", "replace",
                                         "stop", "disconnect", "close", "unknown"),
                         "outcome": ("success", "preemption", "mismatch", "stale",
                                     "drain_timeout", "startup_failed", "cancel_timeout",
                                     "peer_timeout", "peer_error", "error", "unknown")}),
    InstrumentSpec("therapy_voice_pipeline_shutdown_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": ("success", "cancel_timeout", "peer_timeout",
                                      "peer_error", "error", "unknown")}),
    InstrumentSpec("therapy_conversation_turns_total", InstrumentKind.COUNTER, "1",
                   {"modality": _MODALITIES, "language_group": _LANGUAGE_GROUPS,
                    "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_turn_stage_duration_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"stage": _STAGES, "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_turn_ttfa_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"provider": _PROVIDERS, "mode": ("cold", "warm")}),
    InstrumentSpec("therapy_llm_time_to_first_token_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"provider": _PROVIDERS, "operation": _OPERATIONS,
                         "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_stt_realtime_factor", InstrumentKind.HISTOGRAM, "1",
                   {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_stt_redecode_total", InstrumentKind.COUNTER, "1",
                   {"reason": ("unsupported_detection", "low_confidence", "unknown")}),
    InstrumentSpec("therapy_stt_empty_total", InstrumentKind.COUNTER, "1",
                   {"reason": ("no_speech", "empty", "unknown")}),
    InstrumentSpec("therapy_stt_model_load_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_llm_requests_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS,
                    "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_llm_input_tokens_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS}),
    InstrumentSpec("therapy_llm_output_tokens_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS}),
    InstrumentSpec("therapy_llm_retries_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS,
                    "reason": ("rate_limit", "transient", "fallback", "unknown")}),
    InstrumentSpec("therapy_llm_rate_limits_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS}),
    InstrumentSpec("therapy_llm_output_total", InstrumentKind.COUNTER, "1",
                   {"provider": _PROVIDERS, "operation": _OPERATIONS,
                    "result": _LLM_RESULT}),
    InstrumentSpec("therapy_tts_requests_total", InstrumentKind.COUNTER, "1",
                   {"language_group": _LANGUAGE_GROUPS, "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_tts_characters_total", InstrumentKind.COUNTER, "1",
                   {"language_group": _LANGUAGE_GROUPS}),
    InstrumentSpec("therapy_tts_synthesis_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"language_group": _LANGUAGE_GROUPS, "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_tts_time_to_first_audio_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"language_group": _LANGUAGE_GROUPS, "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_tts_realtime_factor", InstrumentKind.HISTOGRAM, "1",
                   {"language_group": _LANGUAGE_GROUPS, "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_barge_ins_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("success", "timeout", "error", "unknown")}),
    InstrumentSpec("therapy_barge_in_stop_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": ("success", "timeout", "error", "unknown")}),
    InstrumentSpec("therapy_webrtc_data_channel_open_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": _CLIENT_OUTCOMES + ("unknown",)}),
    InstrumentSpec("therapy_webrtc_rtt_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"candidate_type": ("relay", "host", "srflx")}),
    InstrumentSpec("therapy_webrtc_jitter_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"candidate_type": ("relay", "host", "srflx")}),
    InstrumentSpec("therapy_webrtc_packet_loss_ratio", InstrumentKind.HISTOGRAM, "1",
                   {"candidate_type": ("relay", "host", "srflx")}),
    InstrumentSpec("therapy_webrtc_connection_total", InstrumentKind.COUNTER, "1",
                   {"candidate_type": ("relay", "host", "srflx"),
                    "outcome": _CLIENT_OUTCOMES + ("unknown",)}),
    InstrumentSpec("therapy_webrtc_bitrate_kbps", InstrumentKind.HISTOGRAM, "1",
                   {"candidate_type": ("relay", "host", "srflx")}),
    InstrumentSpec("therapy_webrtc_bytes_total", InstrumentKind.COUNTER, "By",
                   {"candidate_type": ("relay", "host", "srflx")}),
    InstrumentSpec("therapy_webrtc_concealed_samples_total", InstrumentKind.COUNTER,
                   "1", {"candidate_type": ("relay", "host", "srflx")}),
    # --- persistence/longitudinal ---
    InstrumentSpec("therapy_storage_operations_total", InstrumentKind.COUNTER, "1",
                   {"component": _COMPONENTS, "operation": _STORAGE_OPERATIONS,
                    "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_storage_operation_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"component": _COMPONENTS, "operation": _STORAGE_OPERATIONS,
                    "outcome": _OUTCOMES}),
    InstrumentSpec("therapy_storage_result_rows_total", InstrumentKind.COUNTER, "1",
                   {"component": _COMPONENTS, "operation": _STORAGE_OPERATIONS,
                    "bucket": _COUNT_BUCKETS}),
    InstrumentSpec("therapy_sqlite_busy_total", InstrumentKind.COUNTER, "1",
                   {"component": _COMPONENTS}),
    InstrumentSpec("therapy_sqlite_checkpoint_last_success_unixtime",
                   InstrumentKind.GAUGE, "s", {"component": _COMPONENTS}),
    InstrumentSpec("therapy_sqlite_integrity_last_success_unixtime",
                   InstrumentKind.GAUGE, "s", {"component": _COMPONENTS}),
    InstrumentSpec("therapy_sqlite_wal_bytes", InstrumentKind.GAUGE, "By",
                   {"component": _COMPONENTS}),
    InstrumentSpec("therapy_schema_version", InstrumentKind.GAUGE, "1",
                   {"component": _COMPONENTS}),
    InstrumentSpec("therapy_data_bytes", InstrumentKind.GAUGE, "By",
                   {"kind": ("db", "wal", "audio", "research", "model_cache", "backups")}),
    InstrumentSpec("therapy_session_finalizations_total", InstrumentKind.COUNTER, "1",
                   {"artifact": ("summary", "distill", "recap", "title", "session",
                                 "unknown"),
                    "outcome": ("success", "error", "ownership_skip", "cancelled",
                                "unknown")}),
    InstrumentSpec("therapy_session_finalization_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_session_finalizers_pending", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_context_assembly_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_context_stage_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"stage": ("graph", "episode", "insight", "research", "embed"),
                    "outcome": ("success", "error")}),
    InstrumentSpec("therapy_context_selected_items", InstrumentKind.HISTOGRAM, "1",
                   {"source": ("graph", "edge", "episode", "insight", "research")}),
    InstrumentSpec("therapy_context_filtered_items_total", InstrumentKind.COUNTER,
                   "1", {"source": ("graph", "episode"),
                         "reason": ("status", "boundary", "selection")}),
    InstrumentSpec("therapy_context_rendered_chars", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_distillation_runs_total", InstrumentKind.COUNTER, "1",
                   {"outcome": _OUTCOMES, "idempotent": ("true", "false")}),
    InstrumentSpec("therapy_distillation_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_distillation_candidate_count", InstrumentKind.HISTOGRAM,
                   "1", {"disposition": ("candidate", "promoted", "proposed",
                                            "deferred")}),
    InstrumentSpec("therapy_distillation_validation_failures_total",
                   InstrumentKind.COUNTER, "1",
                   {"category": ("schema", "json", "value")}),
    # --- research/proactivity ---
    InstrumentSpec("therapy_research_ingests_total", InstrumentKind.COUNTER, "1",
                   {"format": ("pdf", "image", "html", "markdown", "text", "unknown"),
                    "outcome": _OUTCOME_BASIC, "deduplicated": ("true", "false")}),
    InstrumentSpec("therapy_research_ingest_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"format": ("pdf", "image", "html", "markdown", "text", "unknown"),
                    "outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_research_source_bytes", InstrumentKind.HISTOGRAM, "By",
                   {"format": ("pdf", "image", "html", "markdown", "text", "unknown")}),
    InstrumentSpec("therapy_research_pages", InstrumentKind.HISTOGRAM, "1",
                   {"format": ("pdf", "image", "html", "markdown", "text", "unknown")}),
    InstrumentSpec("therapy_research_blocks", InstrumentKind.HISTOGRAM, "1",
                   {"kind": ("total", "review")}),
    InstrumentSpec("therapy_proactivity_scheduler_last_tick_unixtime",
                   InstrumentKind.GAUGE, "s"),
    # --- observer health ---
    InstrumentSpec("therapy_llm_capture_records_total", InstrumentKind.COUNTER, "1",
                   {"operation": _OPERATIONS, "status": _CAPTURE_STATUS}),
    InstrumentSpec("therapy_llm_capture_append_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_llm_capture_append_bytes", InstrumentKind.HISTOGRAM, "By"),
    InstrumentSpec("therapy_llm_capture_group_commits_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_llm_capture_group_commit_seconds",
                   InstrumentKind.HISTOGRAM, "s",
                   {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_llm_capture_group_commit_records",
                   InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_llm_capture_queue_depth", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_llm_capture_export_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": _OUTCOMES}),
    InstrumentSpec("therapy_llm_capture_exports_total", InstrumentKind.COUNTER, "1",
                   {"backend": ("phoenix", "unknown"),
                    "outcome": ("accepted", "rejected", "failure")}),
    InstrumentSpec("therapy_llm_capture_oldest_unexported_unixtime",
                   InstrumentKind.GAUGE, "s"),
    InstrumentSpec("therapy_llm_capture_last_export_success_unixtime",
                   InstrumentKind.GAUGE, "s"),
    InstrumentSpec("therapy_llm_capture_journal_bytes", InstrumentKind.GAUGE, "By"),
    InstrumentSpec("therapy_event_loop_lag_seconds", InstrumentKind.HISTOGRAM, "s"),
    InstrumentSpec("therapy_executor_queue_wait_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"workload_class": _WORKLOAD_CLASSES}),
    InstrumentSpec("therapy_executor_active", InstrumentKind.GAUGE, "1",
                   {"workload_class": _WORKLOAD_CLASSES}),
    InstrumentSpec("therapy_executor_completed_total", InstrumentKind.COUNTER, "1",
                   {"workload_class": _WORKLOAD_CLASSES,
                    "outcome": ("success", "error")}),
    InstrumentSpec("therapy_executor_task_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"workload_class": _WORKLOAD_CLASSES,
                    "outcome": ("success", "error")}),
    InstrumentSpec("therapy_event_loop_tasks", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_broad_span_drops_total", InstrumentKind.COUNTER, "1",
                   {"reason": ("unknown_scope", "forbidden_attribute", "queue_full")}),
    InstrumentSpec("therapy_client_events_total", InstrumentKind.COUNTER, "1",
                   {"name": _CLIENT_EVENT_NAMES, "outcome": _CLIENT_OUTCOMES}),
    InstrumentSpec("therapy_client_dropped_events_total", InstrumentKind.COUNTER,
                   "1", {"name": _CLIENT_EVENT_NAMES}),
    InstrumentSpec("therapy_outbound_requests_total", InstrumentKind.COUNTER, "1",
                   {"destination": _DESTINATIONS,
                    "operation": ("get", "post", "put", "patch", "delete", "head",
                                  "options", "other"),
                    "status_class": ("2xx", "3xx", "4xx", "5xx", "none"),
                    "tls": ("true", "false"),
                    "outcome": ("success", "error", "timeout")}),
    InstrumentSpec("therapy_outbound_request_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"destination": _DESTINATIONS,
                    "operation": ("get", "post", "put", "patch", "delete", "head",
                                  "options", "other"),
                    "outcome": ("success", "error", "timeout")}),
    InstrumentSpec("therapy_outbound_bytes", InstrumentKind.HISTOGRAM, "By",
                   {"destination": _DESTINATIONS,
                    "direction": ("request", "response")}),
    InstrumentSpec("therapy_outbound_retry_count", InstrumentKind.HISTOGRAM, "1",
                   {"destination": _DESTINATIONS}),
    # --- O3.1 server routes ---
    InstrumentSpec("therapy_offers_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("fresh", "resumed", "rejected", "conflict",
                                "unavailable")}),
    InstrumentSpec("therapy_voice_signal_total", InstrumentKind.COUNTER, "1",
                   {"operation": ("disconnect", "ice_config", "resumable"),
                    "outcome": ("disconnected", "stale", "unavailable",
                                "success", "resumable", "none")}),
    InstrumentSpec("therapy_http_read_rows_total", InstrumentKind.COUNTER, "1",
                   {"route_class": ("sessions", "session_detail", "graph",
                                    "graph_pending", "research_documents",
                                    "research_query", "proactivity_settings",
                                    "proactivity_digests"),
                    "bucket": _COUNT_BUCKETS}),
    InstrumentSpec("therapy_audio_serve_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("range", "full", "missing")}),
    InstrumentSpec("therapy_audio_serve_bytes", InstrumentKind.HISTOGRAM, "By"),
    # --- O3.2 voice/speech/context ---
    InstrumentSpec("therapy_app_messages_total", InstrumentKind.COUNTER, "1",
                   {"type_class": ("client_ready", "text", "voice_reply",
                                   "reply_language", "unknown", "invalid"),
                    "outcome": ("accepted", "rejected", "queued")}),
    InstrumentSpec("therapy_language_transitions_total", InstrumentKind.COUNTER,
                   "1", {"kind": ("reply_language", "modality", "tts_config"),
                         "outcome": ("pinned", "auto", "unsupported", "changed",
                                     "invalid")}),
    InstrumentSpec("therapy_prompt_builds_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("success", "truncated", "fallback"),
                    "sections": _COUNT_BUCKETS}),
    InstrumentSpec("therapy_vad_utterances_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("speech", "silence", "timeout")}),
    InstrumentSpec("therapy_utterance_audio_seconds", InstrumentKind.HISTOGRAM,
                   "s"),
    InstrumentSpec("therapy_stt_language_probability", InstrumentKind.HISTOGRAM,
                   "1", {"language_group": _LANGUAGE_GROUPS}),
    InstrumentSpec("therapy_persist_total", InstrumentKind.COUNTER, "1",
                   {"artifact": ("turn", "audio", "observation", "inbox"),
                    "outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_persist_bytes", InstrumentKind.HISTOGRAM, "By",
                   {"artifact": ("turn", "audio", "observation", "inbox")}),
    InstrumentSpec("therapy_context_items_total", InstrumentKind.COUNTER, "1",
                   {"source": ("graph", "edge", "episode", "insight", "research"),
                    "bucket": _COUNT_BUCKETS}),
    InstrumentSpec("therapy_context_truncations_total", InstrumentKind.COUNTER,
                   "1", {"source": ("graph", "episode", "insight", "research")}),
    InstrumentSpec("therapy_tts_model_load_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_data_channel_messages_total", InstrumentKind.COUNTER,
                   "1", {"type_class": ("presence", "session", "transcript",
                                        "other"),
                         "outcome": ("sent", "queued", "replayed", "dropped")}),
    # --- O3.3 persistence/graph/research/proactivity/sovereignty ---
    InstrumentSpec("therapy_schema_migrations_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("success", "error", "rolled_back")}),
    InstrumentSpec("therapy_schema_migration_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_backups_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("created", "skipped", "error")}),
    InstrumentSpec("therapy_graph_mutations_total", InstrumentKind.COUNTER, "1",
                   {"operation": ("add_node", "add_edge", "edit", "delete",
                                  "purge", "revalidate", "distill_apply"),
                    "outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_never_store_suppressions_total",
                   InstrumentKind.COUNTER, "1",
                   {"table_class": ("node", "edge", "file", "turn")}),
    InstrumentSpec("therapy_distillation_attempts_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("success", "invalid", "retry", "error")}),
    InstrumentSpec("therapy_distillation_candidates_total",
                   InstrumentKind.COUNTER, "1",
                   {"disposition": ("candidate", "promoted", "proposed",
                                    "deferred")}),
    InstrumentSpec("therapy_insight_transitions_total", InstrumentKind.COUNTER,
                   "1", {"state": ("proposed", "delivered", "snoozed",
                                   "dismissed", "confirmed", "rejected")}),
    InstrumentSpec("therapy_insight_queue_depth", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_observation_backlog", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_observation_oldest_pending_unixtime",
                   InstrumentKind.GAUGE, "s"),
    InstrumentSpec("therapy_insight_backlog", InstrumentKind.GAUGE, "1",
                   {"state": ("queued", "delivered", "snoozed")}),
    InstrumentSpec("therapy_insight_oldest_pending_unixtime",
                   InstrumentKind.GAUGE, "s",
                   {"state": ("queued", "delivered", "snoozed")}),
    InstrumentSpec("therapy_graph_revalidation_backlog", InstrumentKind.GAUGE, "1",
                   {"kind": ("node", "edge")}),
    InstrumentSpec("therapy_disk_free_bytes", InstrumentKind.GAUGE, "By"),
    InstrumentSpec("therapy_disk_free_inodes", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_storage_inspections_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_research_stage_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"stage": ("validate", "extract", "ocr", "artifact",
                                   "db", "embed", "index"),
                         "outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_research_queries_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("hit", "no_hit", "error")}),
    InstrumentSpec("therapy_research_query_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": ("hit", "no_hit", "error")}),
    InstrumentSpec("therapy_research_query_candidates", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_research_query_results", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_research_query_top_score", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_research_reindex_total", InstrumentKind.COUNTER, "1",
                   {"outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_research_reindex_documents", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_research_reindex_blocks", InstrumentKind.HISTOGRAM, "1",
                   {"kind": ("total", "indexed", "review_excluded")}),
    InstrumentSpec("therapy_research_unindexed_documents", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_research_divergence_total", InstrumentKind.COUNTER,
                   "1", {"kind": ("db_without_file", "file_without_db")}),
    InstrumentSpec("therapy_ocr_runs_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("success", "timeout", "error", "skipped")}),
    InstrumentSpec("therapy_ocr_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"outcome": ("success", "timeout", "error")}),
    InstrumentSpec("therapy_ocr_pages_total", InstrumentKind.COUNTER, "1",
                   {"outcome": ("success", "timeout", "error", "skipped")}),
    InstrumentSpec("therapy_ocr_pixels", InstrumentKind.HISTOGRAM, "1"),
    InstrumentSpec("therapy_ocr_blocks", InstrumentKind.HISTOGRAM, "1",
                   {"kind": ("total", "review")}),
    InstrumentSpec("therapy_embedding_batches_total", InstrumentKind.COUNTER,
                   "1", {"cache": ("cold", "warm"),
                         "outcome": ("success", "error")}),
    InstrumentSpec("therapy_embedding_seconds", InstrumentKind.HISTOGRAM, "s",
                   {"cache": ("cold", "warm")}),
    InstrumentSpec("therapy_embedding_model_load_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_embedding_items", InstrumentKind.HISTOGRAM, "1",
                   {"cache": ("cold", "warm")}),
    InstrumentSpec("therapy_embedding_characters", InstrumentKind.HISTOGRAM, "1",
                   {"cache": ("cold", "warm")}),
    InstrumentSpec("therapy_embedding_characters_per_second",
                   InstrumentKind.HISTOGRAM, "1",
                   {"cache": ("cold", "warm")}),
    InstrumentSpec("therapy_proactivity_ticks_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_proactivity_tick_seconds", InstrumentKind.HISTOGRAM,
                   "s", {"outcome": ("success", "error")}),
    InstrumentSpec("therapy_proactivity_jobs_total", InstrumentKind.COUNTER, "1",
                   {"stage": ("due", "claimed", "delivered", "retry",
                              "finalized", "suppressed"),
                    "channel": ("push", "greeting", "check_in", "digest", "unknown")}),
    InstrumentSpec("therapy_proactivity_oldest_due_age_seconds",
                   InstrumentKind.GAUGE, "s"),
    InstrumentSpec("therapy_proactivity_queue_jobs", InstrumentKind.GAUGE, "1",
                   {"state": ("pending", "retry", "processing"),
                    "channel": ("push", "greeting", "check_in", "digest")}),
    InstrumentSpec("therapy_proactivity_suppressions_total", InstrumentKind.COUNTER,
                   "1", {"reason": ("channel_disabled", "never_initiate",
                                      "nothing_due", "unknown"),
                         "channel": ("push", "greeting", "check_in", "digest",
                                     "unknown")}),
    InstrumentSpec("therapy_webpush_deliveries_total", InstrumentKind.COUNTER,
                   "1", {"status_class": ("2xx", "4xx", "5xx", "timeout",
                                          "invalid")}),
    InstrumentSpec("therapy_webpush_ttl_seconds", InstrumentKind.HISTOGRAM, "s"),
    InstrumentSpec("therapy_webpush_active_subscriptions", InstrumentKind.GAUGE, "1"),
    InstrumentSpec("therapy_webpush_subscription_events_total",
                   InstrumentKind.COUNTER, "1",
                   {"event": ("created", "refreshed", "invalidated", "key_created")}),
    InstrumentSpec("therapy_sovereignty_stages_total", InstrumentKind.COUNTER,
                   "1", {"operation": ("export", "restore", "delete"),
                         "stage": _SOVEREIGNTY_STAGES, "outcome": _OUTCOME_BASIC}),
    InstrumentSpec("therapy_sovereignty_rollbacks_total", InstrumentKind.COUNTER,
                   "1", {"outcome": ("attempted", "succeeded", "failed")}),
)

#: Fast lookup by name; duplicate names are a manifest bug caught by tests.
INSTRUMENT_INDEX: dict[str, InstrumentSpec] = {
    spec.name: spec for spec in INSTRUMENTS
}
